### ISSUE TITLE
[testcontainers]: Unable to run tests with latest docker for mac

### ISSUE THREAD

**Issue by halyph** [halyph/mind-flow#133]
## Issue

Running testcontaines on Mac and getting the folowing error:

```java
[testcontainers-ryuk] WARN  o.t.utility.ResourceReaper - Can not connect to Ryuk at localhost:32768
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at org.testcontainers.utility.ResourceReaper.lambda$null$1(ResourceReaper.java:121)
	at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27)
	at org.testcontainers.utility.ResourceReaper.lambda$start$2(ResourceReaper.java:119)
	at java.lang.Thread.run(Thread.java:748)
```

Scala testcontainers library:  
`lazy val testcontainers = "com.dimafeng" %% "testcontainers-scala-scalatest" % 0.36.1` 

### Docker Desktop

![Screen Shot 2020-11-24 at 6 02 38 PM](https://user-images.githubusercontent.com/241654/100127315-464b5b00-2e7f-11eb-9cb6-276f1517ab5f.png)

```bash
$ docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.2
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

## Reference

- Solution [Unable to run tests with latest docker for mac](https://github.com/testcontainers/testcontainers-java/issues/3291)

**Comment by halyph** [comment]
## Fix

Disable _Experimental Feature_ "**Use gRPC FUSE for file sharing**"

![Screen Shot 2020-11-24 at 6 07 28 PM](https://user-images.githubusercontent.com/241654/100127991-fa4ce600-2e7f-11eb-9078-c026e4b0aec1.png)
