### ISSUE TITLE
Python3 is not configured for Tk

### ISSUE THREAD

**Issue by halyph** [halyph/mind-flow#178]
```
➜ python3 -m tkinter
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'
```

Fix

```bash
brew install python-tk
```

**Comment by halyph** [comment]
https://formulae.brew.sh/formula/python-tk@3.11#default

**Comment by halyph** [comment]
See https://stackoverflow.com/questions/36760839/why-does-python-installed-via-homebrew-not-include-tkinter

**Comment by halyph** [comment]
This one is good https://stackoverflow.com/questions/76105218/why-does-tkinter-or-turtle-seem-to-be-missing-or-broken-shouldnt-it-be-part
